#spring:
#   data:
#        elasticsearch:
#            cluster-name: #默认为elasticsearch
#            cluster-nodes: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
#            properties:
#                path:
#                  logs: ./elasticsearch/log #elasticsearch日志存储目录
#                  data: /es/5.6.2/dd #elasticsearch数据存储目录

spring:
    data:
        elasticsearch:
#            cluster-name: nini
            cluster-nodes: 127.0.0.1:9300
            local: false
            repositories:
                enable: true

spring:
  elasticsearch:
    host: 127.0.0.1
    port: 9200